package com.cho.app.mapper;

import com.cho.app.model.Notice;
import com.cho.app.model.NoticeCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    long countByExample(NoticeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    int deleteByExample(NoticeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    int deleteByPrimaryKey(Integer idx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    int insert(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    int insertSelective(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    List<Notice> selectByExample(NoticeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    Notice selectByPrimaryKey(Integer idx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    int updateByExampleSelective(@Param("record") Notice record, @Param("example") NoticeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    int updateByExample(@Param("record") Notice record, @Param("example") NoticeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    int updateByPrimaryKeySelective(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    int updateByPrimaryKey(Notice record);
}