package com.cho.app.mapper;

import com.cho.app.model.User;
import com.cho.app.model.UserCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.cho.app.model.UserWithBLOBs;

public interface UserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Mon Feb 03 16:29:56 JST 2020
	 */
	long countByExample(UserCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Mon Feb 03 16:29:56 JST 2020
	 */
	int deleteByExample(UserCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Mon Feb 03 16:29:56 JST 2020
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Mon Feb 03 16:29:56 JST 2020
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Mon Feb 03 16:29:56 JST 2020
	 */
	List<User> selectByExample(UserCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Mon Feb 03 16:29:56 JST 2020
	 */
	int updateByExampleSelective(@Param("record") User record, @Param("example") UserCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Mon Feb 03 16:29:56 JST 2020
	 */
	int updateByExample(@Param("record") User record, @Param("example") UserCriteria example);
}