package com.cho.app.model;

import java.util.Date;

public class Notice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.idx
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    private Integer idx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.status
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.title
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.contents
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    private String contents;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.priory
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    private String priory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.target_group
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    private String targetGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.post_start
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    private Date postStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.post_end
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    private Date postEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.insert_user
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    private String insertUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.insert_time
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    private Date insertTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.update_user
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.update_time
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.idx
     *
     * @return the value of notice.idx
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public Integer getIdx() {
        return idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.idx
     *
     * @param idx the value for notice.idx
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public void setIdx(Integer idx) {
        this.idx = idx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.status
     *
     * @return the value of notice.status
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.status
     *
     * @param status the value for notice.status
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.title
     *
     * @return the value of notice.title
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.title
     *
     * @param title the value for notice.title
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.contents
     *
     * @return the value of notice.contents
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public String getContents() {
        return contents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.contents
     *
     * @param contents the value for notice.contents
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public void setContents(String contents) {
        this.contents = contents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.priory
     *
     * @return the value of notice.priory
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public String getPriory() {
        return priory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.priory
     *
     * @param priory the value for notice.priory
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public void setPriory(String priory) {
        this.priory = priory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.target_group
     *
     * @return the value of notice.target_group
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public String getTargetGroup() {
        return targetGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.target_group
     *
     * @param targetGroup the value for notice.target_group
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public void setTargetGroup(String targetGroup) {
        this.targetGroup = targetGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.post_start
     *
     * @return the value of notice.post_start
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public Date getPostStart() {
        return postStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.post_start
     *
     * @param postStart the value for notice.post_start
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public void setPostStart(Date postStart) {
        this.postStart = postStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.post_end
     *
     * @return the value of notice.post_end
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public Date getPostEnd() {
        return postEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.post_end
     *
     * @param postEnd the value for notice.post_end
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public void setPostEnd(Date postEnd) {
        this.postEnd = postEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.insert_user
     *
     * @return the value of notice.insert_user
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public String getInsertUser() {
        return insertUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.insert_user
     *
     * @param insertUser the value for notice.insert_user
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public void setInsertUser(String insertUser) {
        this.insertUser = insertUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.insert_time
     *
     * @return the value of notice.insert_time
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.insert_time
     *
     * @param insertTime the value for notice.insert_time
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.update_user
     *
     * @return the value of notice.update_user
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.update_user
     *
     * @param updateUser the value for notice.update_user
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.update_time
     *
     * @return the value of notice.update_time
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.update_time
     *
     * @param updateTime the value for notice.update_time
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}