package com.cho.app.model;

import java.util.Date;

public class UserGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.uuid
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.status
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.code
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.name
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.insert_user
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    private String insertUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.insert_time
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    private Date insertTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.update_user
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_group.update_time
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.uuid
     *
     * @return the value of user_group.uuid
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.uuid
     *
     * @param uuid the value for user_group.uuid
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.status
     *
     * @return the value of user_group.status
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.status
     *
     * @param status the value for user_group.status
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.code
     *
     * @return the value of user_group.code
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.code
     *
     * @param code the value for user_group.code
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.name
     *
     * @return the value of user_group.name
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.name
     *
     * @param name the value for user_group.name
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.insert_user
     *
     * @return the value of user_group.insert_user
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public String getInsertUser() {
        return insertUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.insert_user
     *
     * @param insertUser the value for user_group.insert_user
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public void setInsertUser(String insertUser) {
        this.insertUser = insertUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.insert_time
     *
     * @return the value of user_group.insert_time
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.insert_time
     *
     * @param insertTime the value for user_group.insert_time
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.update_user
     *
     * @return the value of user_group.update_user
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.update_user
     *
     * @param updateUser the value for user_group.update_user
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_group.update_time
     *
     * @return the value of user_group.update_time
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_group.update_time
     *
     * @param updateTime the value for user_group.update_time
     *
     * @mbg.generated Mon Feb 03 16:29:56 JST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}